import{buildPromptByTool,buildProjectSummary,getToolTitle}from"./prompts.js";import{runGeminiPrompt}from"./gemini.js";import{deleteProject,exportProject,getProjects,isLocalStorageAvailable,normalizeImportedProject,saveProject}from"./storage.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const els={navToggle:$("#navToggle"),navLinks:$("#navLinks"),storageStatus:$("#storageStatus"),storageNote:$("#storageNote"),savedCount:$("#savedCount"),savedList:$("#savedProjectsList"),templateType:$("#templateType"),templateNote:$("#templateNote"),freeCard:$("#freeModeCard"),geminiCard:$("#geminiModeCard"),apiKeyField:$("#apiKeyField"),apiKey:$("#geminiApiKey"),model:$("#geminiModel"),clearKey:$("#clearApiKey"),outputTitle:$("#outputTitle"),outputText:$("#outputText"),outputStatus:$("#outputStatus"),copy:$("#copyOutput"),download:$("#downloadOutput"),loadDemo:$("#loadDemo"),clear:$("#clearForm"),saveTop:$("#saveProjectTop"),save:$("#saveProject"),exportCurrent:$("#exportCurrentProject"),importFile:$("#importProjectFile"),qualityScore:$("#qualityScore"),qualityFill:$("#qualityFill"),qualityMessage:$("#qualityMessage")};
let latestResult="",latestPrompt="",latestSummary="",latestJson="",latestOutput="",latestOutputName="animedebt-output",activeTab="result",currentProjectId=null,currentProjectCreatedAt=null,isGenerating=false;
const templateNotes={"anime-trailer":"Builds a cinematic trailer with narration, scene list, shot list, prompts, sound, and edit rhythm.","episode-one":"Builds a pilot episode structure with world introduction, character motivation, conflict, and ending hook.","mystery-hook":"Builds a mystery-first short with unanswered questions, clues, red herrings, and payoff options.","character-reveal":"Builds a dramatic character entrance with visual identity, dialogue, power hints, and audience hook.","dark-fantasy-short":"Builds a moody dark fantasy short with atmosphere, lore, dramatic pacing, and production prompts."};
const ids=["projectTitle","storyIdea","genre","style","targetFormat","platform","length","detailLevel","tone","mainCharacter","mainMystery","worldRules","avoid","templateType"];
const demo={projectTitle:"Clockworld Kingdom",storyIdea:"A clockwork kingdom called Aurelis where the sun never rises. Every clock in the city obeys the Crown, until one child sees the Grand Clock Tower move backward to 11:59 and discovers that the morning was stolen.",genre:"Dark fantasy mystery",style:"Cinematic anime, dark blue and violet night palette, high contrast, wet cobblestones, fog, steam, glowing cyan clocklight",targetFormat:"Trailer",platform:"YouTube Shorts",length:"60 seconds",detailLevel:"studio-detailed",tone:"Serious, mysterious, epic, tense, emotional",mainCharacter:"A quiet child who notices impossible changes in the clocks while everyone else obeys the bells",mainMystery:"Who stole the morning, and why does the Crown forbid people from saying the word sunrise?",worldRules:"Aurelis is night-only. No true sunlight appears outdoors. The city runs on bells, shifts, clocks, steam trains, guards, and strict schedules. Cyan clocklight signals forbidden time glitches.",avoid:"No golden sunlight outdoors, no comedy tone, no modern cars, no sci-fi laser guns, no random futuristic neon city, no changing the night-only rule, no empty streets"};
els.navToggle?.addEventListener("click",()=>els.navLinks?.classList.toggle("open"));els.navLinks?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>els.navLinks.classList.remove("open")));addEventListener("keydown",e=>{if(e.key==="Escape")els.navLinks?.classList.remove("open")});
if(els.storageStatus)els.storageStatus.textContent=isLocalStorageAvailable()?"Available":"Unavailable";if(els.storageNote&&!isLocalStorageAvailable())els.storageNote.textContent="Your browser is blocking localStorage, so saving projects will not work here.";
els.templateType?.addEventListener("change",updateTemplateNote);$$("input[name='aiMode']").forEach(i=>i.addEventListener("change",()=>{const m=getMode();els.freeCard?.classList.toggle("active",m==="free");els.geminiCard?.classList.toggle("active",m==="gemini");els.apiKeyField?.classList.toggle("hidden",m!=="gemini")}));
$$("[data-tool]").forEach(b=>b.addEventListener("click",()=>generateOutput(b.dataset.tool)));
els.clearKey?.addEventListener("click",()=>{if(els.apiKey)els.apiKey.value="";show("API key cleared","The Gemini API key input has been cleared. It was not saved locally.","success");els.outputStatus.textContent="Key cleared"});
$$("[data-tab]").forEach(b=>b.addEventListener("click",()=>{setTab(b.dataset.tab);renderTab()}));
$$(".quick-template").forEach(c=>c.addEventListener("click",()=>{els.templateType.value=c.dataset.template;updateTemplateNote();updateQuality();$("#generator")?.scrollIntoView({behavior:"smooth"})}));
ids.forEach(id=>{const el=$("#"+id);["input","change"].forEach(ev=>el?.addEventListener(ev,()=>{el.classList.remove("invalid");if(currentProjectId)els.outputStatus.textContent="Unsaved edits";updateQuality()}))});
els.loadDemo?.addEventListener("click",()=>{Object.entries(demo).forEach(([id,v])=>{const el=$("#"+id);if(el)el.value=v});els.templateType.value="anime-trailer";currentProjectId=null;currentProjectCreatedAt=null;updateTemplateNote();updateQuality();show("Demo loaded","Demo project loaded. Click Generate Full Pack to create a production prompt, or switch to Gemini Key Mode to run it directly.","success");els.outputStatus.textContent="Demo ready"});
els.clear?.addEventListener("click",clearWorkspace);[els.saveTop,els.save].filter(Boolean).forEach(b=>b.addEventListener("click",saveCurrentProject));els.exportCurrent?.addEventListener("click",exportCurrentProject);
els.importFile?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());const saved=saveProject(normalizeImportedProject(payload));renderSaved();loadProject(saved);show("Imported project",`"${saved.title||"Untitled project"}" was imported and loaded.`,"success");els.outputStatus.textContent="Imported"}catch(err){show("Import failed",err.message||"Could not import that JSON file.","error");els.outputStatus.textContent="Import failed"}finally{e.target.value=""}});
els.savedList?.addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.dataset.id,action=b.dataset.action,project=getProjects().find(p=>p.id===id);if(action==="load"&&project){loadProject(project);show("Project loaded",`"${project.title||"Untitled project"}" is now loaded in the generator.`,"success");els.outputStatus.textContent="Loaded";$("#generator")?.scrollIntoView({behavior:"smooth"})}if(action==="export"&&project){download(`${safe(project.title||"animedebt-project")}-project.json`,exportProject(project),"application/json")}if(action==="delete"){deleteProject(id);if(currentProjectId===id){currentProjectId=null;currentProjectCreatedAt=null}renderSaved();show("Project deleted","The saved project was deleted from this browser.","success");els.outputStatus.textContent="Deleted"}});
els.copy?.addEventListener("click",async()=>{if(!latestOutput)return temp(els.copy,"Nothing yet");try{await navigator.clipboard.writeText(latestOutput)}catch{fallbackCopy(latestOutput)}temp(els.copy,"Copied")});
els.download?.addEventListener("click",()=>{if(!latestOutput)return temp(els.download,"Nothing yet");const ext=activeTab==="json"?"json":"md";download(`${latestOutputName}-${activeTab}.${ext}`,latestOutput,activeTab==="json"?"application/json":"text/markdown");temp(els.download,"Downloaded")});
function collect(){return{id:currentProjectId,title:val("projectTitle"),storyIdea:val("storyIdea"),genre:val("genre"),style:val("style"),targetFormat:val("targetFormat"),platform:val("platform"),length:val("length"),detailLevel:val("detailLevel"),tone:val("tone"),mainCharacter:val("mainCharacter"),mainMystery:val("mainMystery"),worldRules:val("worldRules"),avoid:val("avoid"),templateType:val("templateType"),aiMode:getMode(),geminiModel:els.model?.value||"gemini-3.1-flash-lite"}}
async function generateOutput(tool){if(isGenerating)return;const p=collect(),v=validate(p);if(!v.valid){show("Missing story idea",v.message,"error");v.field?.classList.add("invalid");v.field?.focus();els.outputStatus.textContent="Needs story idea";return}const title=getToolTitle(tool),prompt=buildPromptByTool(tool,p),summary=buildProjectSummary(p);latestPrompt=prompt;latestSummary=summary;latestOutputName=safe(`${p.title||"animedebt"}-${title}`);try{setLoading(true);if(getMode()==="gemini"){const key=els.apiKey?.value.trim();if(!key)throw new Error("Paste a Gemini API key first, or switch back to Free Prompt Mode.");show("Generating with Gemini","Sending your production prompt to Gemini. The API key is used only for this request and is not saved.","success");const response=await runGeminiPrompt({apiKey:key,prompt,model:p.geminiModel});latestResult=response.text;latestJson=JSON.stringify({generatedAt:new Date().toISOString(),mode:"gemini",model:response.model,selectedTool:tool,selectedToolTitle:title,project:p,prompt,result:response.text,raw:response.raw},null,2);setTab("result");renderTab(title);els.outputStatus.textContent="Gemini result"}else{latestResult=prompt+"\n\n---\nFREE PROMPT MODE: Copy this prompt into ChatGPT, Gemini, Claude, or another AI tool.";latestJson=JSON.stringify({generatedAt:new Date().toISOString(),mode:"free",selectedTool:tool,selectedToolTitle:title,project:p,prompt},null,2);setTab("result");renderTab(title);els.outputStatus.textContent="Prompt ready"}updateMini(tool)}catch(err){show("Generation failed",err.message||"Something went wrong while generating.","error");els.outputStatus.textContent="Error"}finally{setLoading(false)}}
function saveCurrentProject(){const p=collect(),v=validate(p);if(!v.valid){show("Cannot save yet",v.message,"error");v.field?.classList.add("invalid");v.field?.focus();return}try{const saved=saveProject({...p,id:currentProjectId,createdAt:currentProjectCreatedAt,outputs:{latestResult,latestPrompt,latestSummary,latestJson,activeTab,latestOutputName}});currentProjectId=saved.id;currentProjectCreatedAt=saved.createdAt;renderSaved();show("Project saved",`"${saved.title||"Untitled project"}" was saved locally in this browser. Your Gemini API key was not saved.`,"success");els.outputStatus.textContent="Saved"}catch(err){show("Save failed",err.message||"Could not save this project.","error");els.outputStatus.textContent="Save failed"}}
function exportCurrentProject(){const p=collect(),v=validate(p);if(!v.valid){show("Cannot export yet",v.message,"error");v.field?.classList.add("invalid");v.field?.focus();return}const item={...p,id:currentProjectId||crypto.randomUUID(),createdAt:currentProjectCreatedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),outputs:{latestResult,latestPrompt,latestSummary,latestJson,activeTab,latestOutputName}};download(`${safe(p.title||"animedebt-project")}-project.json`,exportProject(item),"application/json");els.outputStatus.textContent="Exported"}
function loadProject(p){const map={projectTitle:p.title||"",storyIdea:p.storyIdea||"",genre:p.genre||"Dark fantasy mystery",style:p.style||"",targetFormat:p.targetFormat||"Trailer",platform:p.platform||"YouTube Shorts",length:p.length||"60 seconds",detailLevel:p.detailLevel||"studio-detailed",tone:p.tone||"",mainCharacter:p.mainCharacter||"",mainMystery:p.mainMystery||"",worldRules:p.worldRules||"",avoid:p.avoid||"",templateType:p.templateType||"anime-trailer"};Object.entries(map).forEach(([id,v])=>{const el=$("#"+id);if(el)el.value=v});currentProjectId=p.id||null;currentProjectCreatedAt=p.createdAt||null;latestResult=p.outputs?.latestResult||"";latestPrompt=p.outputs?.latestPrompt||"";latestSummary=p.outputs?.latestSummary||buildProjectSummary(collect());latestJson=p.outputs?.latestJson||JSON.stringify({project:p},null,2);latestOutputName=p.outputs?.latestOutputName||safe(p.title||"animedebt-output");setTab(p.outputs?.activeTab||"summary");updateTemplateNote();updateQuality();renderTab();renderSaved()}
function clearWorkspace(){ids.forEach(id=>{const el=$("#"+id);if(!el)return;if(el.tagName==="SELECT")el.selectedIndex=0;else el.value="";el.classList.remove("invalid")});latestResult=latestPrompt=latestSummary=latestJson=latestOutput="";currentProjectId=null;currentProjectCreatedAt=null;setTab("result");updateTemplateNote();updateQuality();updateMini("reset");show("Cleared","Form cleared. Add a new story idea to generate a production prompt.","success");els.outputStatus.textContent="Ready";renderSaved()}
function renderSaved(){const projects=getProjects();if(els.savedCount)els.savedCount.textContent=`${projects.length} saved`;if(!els.savedList)return;if(!projects.length){els.savedList.innerHTML='<p class="empty">No saved projects yet. Fill the generator and click Save.</p>';return}els.savedList.innerHTML=projects.map(p=>`<article class="saved-project ${p.id===currentProjectId?"active":""}"><div><span class="mini">${escapeHtml(p.templateType||"anime-trailer")}</span><h4>${escapeHtml(p.title||"Untitled project")}</h4><p>${escapeHtml(p.storyIdea||"No story idea saved.")}</p><small>Updated ${formatDate(p.updatedAt||p.createdAt)}</small></div><div class="saved-project-actions"><button class="small" data-action="load" data-id="${p.id}">Load</button><button class="small" data-action="export" data-id="${p.id}">Export</button><button class="small danger" data-action="delete" data-id="${p.id}">Delete</button></div></article>`).join("")}
function renderTab(title=null){const map={result:latestResult,prompt:latestPrompt,summary:latestSummary,json:latestJson};latestOutput=map[activeTab]||"Generate a module first, then switch between Result, Prompt, Summary, and JSON.";show({result:title||"Generated Result",prompt:"Prompt Sent / Copy Prompt",summary:"Project Summary",json:"Project JSON"}[activeTab]||"Generated Output",latestOutput,"success")}
function validate(p){const field=$("#storyIdea");if(!p.storyIdea||p.storyIdea.length<8)return{valid:false,field,message:'Please add a clearer story idea first.\n\nExample:\n"A clockwork kingdom where the sun never rises, and a child discovers the largest clock moving backward."\n\nThe idea does not need to be perfect, but it needs enough detail for useful outputs.'};return{valid:true}}
function updateQuality(){const p=collect(),checks=[p.title,p.storyIdea,p.genre,p.style,p.targetFormat,p.platform,p.length,p.tone,p.mainCharacter,p.mainMystery,p.worldRules,p.avoid],score=Math.round(checks.filter(x=>x&&x.length>=3).length/checks.length*100);if(els.qualityScore)els.qualityScore.textContent=`${score}%`;if(els.qualityFill)els.qualityFill.style.width=`${score}%`;if(els.qualityMessage)els.qualityMessage.textContent=score<25?"Start with the story idea, tone, and main mystery.":score<55?"Good start. Add world rules, style, and avoid list for stronger outputs.":score<85?"Strong setup. Fill the remaining fields for more consistent production prompts.":"Production-ready. Generate a full pack or specific module."}
function updateMini(tool){const m={full:["Generated","Generated","Generated","Generated"],storyDebts:["Generated","Pending","Pending","Updated"],trailer:["Updated","Pending","Generated","Pending"],storyboard:["Updated","Generated","Pending","Pending"],imagePrompts:["Pending","Updated","Generated","Pending"],videoPrompts:["Pending","Generated","Generated","Pending"],soundDesign:["Pending","Pending","Updated","Pending"],continuity:["Updated","Pending","Pending","Generated"],reset:["Not generated yet","Not generated yet","Not generated yet","Not generated yet"]}[tool]||["Updated","Updated","Updated","Updated"];$$(".mini-grid strong").forEach((el,i)=>el.textContent=m[i])}
function show(title,text,type="success"){if(els.outputTitle)els.outputTitle.textContent=title;if(els.outputText)els.outputText.textContent=text;$("#outputCard")?.classList.remove("success","error");$("#outputCard")?.classList.add(type);latestOutput=text}
function setLoading(on){isGenerating=on;$$(`[data-tool]`).forEach(b=>b.disabled=on);if(els.outputStatus){els.outputStatus.classList.toggle("loading",on);if(on)els.outputStatus.textContent="Generating..."}}
function setTab(tab){activeTab=tab||"result";$$("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===activeTab))}
function updateTemplateNote(){if(els.templateNote)els.templateNote.textContent=templateNotes[els.templateType?.value]||templateNotes["anime-trailer"]}
function val(id){return $("#"+id)?.value.trim()||""}function getMode(){return $('input[name="aiMode"]:checked')?.value||"free"}
function temp(btn,text){const o=btn.textContent;btn.textContent=text;btn.disabled=true;setTimeout(()=>{btn.textContent=o;btn.disabled=false},1200)}
function download(filename,content,mime="text/markdown"){const blob=new Blob([content],{type:`${mime};charset=utf-8`}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function fallbackCopy(text){const t=document.createElement("textarea");t.value=text;t.setAttribute("readonly","");t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}
function safe(name){return String(name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,80)||"animedebt-output"}
function formatDate(v){try{return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return"unknown date"}}
function escapeHtml(v){return String(v).slice(0,220).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
updateTemplateNote();updateQuality();renderSaved();console.log("AnimeDebt Studio Phase 7 loaded. Gemini BYOK mode is active.");